'use client'

import type { Metadata } from 'next'
import { Global } from '@emotion/react'
import globalStyles from '@/shared/styles/globalStyles'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const client = new QueryClient({
  defaultOptions: {},
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>
        <QueryClientProvider client={client}>
          <Global styles={globalStyles} />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  )
}
